SUBROUTINE ANORMALA(T1X,T1Y,T1Z,T2X,T2Y,T2Z,T3X,T3Y,T3Z,T4X,T4Y,T4Z,ENX,ENY,ENZ)
! CALCULATES NORMAL ON THE TRACK WALL , DIRECTED IN THE TRACK
IMPLICIT REAL (8) (A-H, O-Z)

PI=4.*ATAN(1.)
DELTAX1=T1X-T4X
DELTAY1=T1Y-T4Y
DELTAZ1=T1Z-T4Z
  ANORMA=SQRT(DELTAX1**2+DELTAY1**2+DELTAZ1**2)
  DELTAX1= DELTAX1/ANORMA
 DELTAY1= DELTAY1/ANORMA
 DELTAZ1= DELTAZ1/ANORMA
 DELTAX2=T2X-T3X
 DELTAY2=T2Y-T3Y
 DELTAZ2=T2Z-T3Z
  ANORMA=SQRT(DELTAX2**2+DELTAY2**2+DELTAZ2**2)
  DELTAX2= DELTAX2/ANORMA
 DELTAY2= DELTAY2/ANORMA
 DELTAZ2= DELTAZ2/ANORMA
 ENX=DELTAY1*DELTAZ2-DELTAZ1*DELTAY2
ENY=DELTAZ1*DELTAX2-DELTAX1*DELTAZ2
ENZ=DELTAX1*DELTAY2-DELTAY1*DELTAX2
 ANORMA=SQRT(ENX**2+ENY**2+ENZ**2)
ENX=ENX/ANORMA
ENY=ENY/ANORMA
ENZ=ENZ/ANORMA
END SUBROUTINE ANORMALA
