SUBROUTINE DETPROTON(ENEPROTON,REMOVED,TIME_ETCHING,THETA,DV,DM,INDICATOR,DEPTH,IAX, crnideo)

!SUBROUTINE CALCULATES TRACK PARAMETERS
!PLOTTING OF THE SHAPE OF THE WALL AND TRACK OPENING CONTOURE IN LR115 AND CR39 DETECTORS
!USE LIGHT PROPAGATION TO GET OPTICAL APPEARANCE  

 
 	DOUBLE PRECISION , ALLOCATABLE :: TRAGX(:),TRAGY1(:),TRAGY2(:),PRAVA(:)
	DOUBLE PRECISION , ALLOCATABLE :: PRAVAN(:,:),PRXK(:),PRYK(:)

	DOUBLE PRECISION , ALLOCATABLE :: X1(:),Y1(:),DELTA(:),VT_OVER_VB(:)
	DOUBLE PRECISION , ALLOCATABLE :: RTRAGX(:),RTRAGY(:), RX(:),RY(:)
	REAL, DIMENSION (11000) :: ENES,RAN  !ENERGY OF PROTONS AND RANGES IN DETECTOR


	DOUBLE PRECISION , ALLOCATABLE ::PRESNGX(:),PRESNGY(:),PRESNDX(:),PRESNDY(:),DISTANCE(:)
	DOUBLE PRECISION , ALLOCATABLE :: KORX(:),KORY(:),KOR_Y(:),KORZ(:)
	DOUBLE PRECISION , ALLOCATABLE :: KOORDINATE_3DX(:),KOORDINATE_3DY(:),KOORDINATE_3DZ(:)
	DOUBLE PRECISION , ALLOCATABLE :: YY(:,:)
	DOUBLE PRECISION , ALLOCATABLE :: FINRES(:,:)
	DOUBLE PRECISION XPRES1,YPRES1,XPRES2,YPRES2 ,VB
	DOUBLE PRECISION REMOVED,THETA,RANGE,XC, XP,YP,DINTERVAL,THEKRAJ,DELTAZ
	DOUBLE PRECISION RASTD,SKSL,DB,TIME,YT,X ,DINTERVAL1
	DOUBLE PRECISION STEP,STEP1, TIME_ETCHING,Z0
	DOUBLE PRECISION OVERETCHED_THICKNESS,PI,XMAX,ORAKUGAO,AINTERVAL
	DOUBLE PRECISION 	AKO, ANO, RASTOMAX,Z00,DUBINA
    CHARACTER *1, CONSTANTS	,THREEDIM
	
	ALLOCATABLE XOTVOR(:),YOTVOR(:)
  	COMMON VB,PI,/ZONA2/A1,A2,A3,A4,A5/ZONA1/RANGE/ZONA3/KOJAF,CONSTANTS
 

OPEN(766,FILE='Contour.dat')	
OPEN(765,FILE='TRACK_COORDINATES.DAT')
OPEN(1519,FILE='3_D.DAT') 
OPEN(11,FILE='Rang_cr_P.DAT')	!CONTAINS DATA ON RANGE/ENERGY FROM SRIM
  
INDICATOR=1		!DEVELOPING THE TRACK INDICATOR=1
				!IF INDICATOR NEQ TO 1 THERE IS NOT TRACK DEVELOPMENT	


 THREEDIM='Y'
					 
PRINT *, 'HOW MANY HORIZONTAL PLANES INTERSECTING THE TRACK DO YOU WISH'
READ *, KRUGA
 
PRINT *,'HOW MANY POINTS PER ONE INTERSECTION' 
READ *, NPOINT
 
N3D=(2*NPOINT-2)*KRUGA  !TOTAL NUMBER DESCRIBING TRACK IN 3-D 
ALLOCATE(KORX(KRUGA*NPOINT),KORY(KRUGA*NPOINT),KOR_Y(KRUGA*NPOINT),KORZ(KRUGA*NPOINT))
ALLOCATE(KOORDINATE_3DX(N3D),KOORDINATE_3DY(N3D),KOORDINATE_3DZ(N3D))
ALLOCATE (YY(KRUGA*NPOINT,4) )

ALLOCATE (PRESNGX(1:KRUGA),PRESNGY(1:KRUGA),PRESNDX(1:KRUGA),PRESNDY(1:KRUGA),DISTANCE(1:KRUGA))

DO I=1,11000	
READ (11,*) ENES(I),RAN(I)	     
END DO	 	
	             
REWIND 11

VMAX=-1.
XX=0.d0


DO		!THIS LOOP FOUND MAXIMAL VALUE OF Vt FUNCTION 
V=VT(DBLE(XX))
  	IF(V>VMAX)then
	xmax=xx
	VMAX=V
	end if
XX=XX+0.01
IF(XX>10.)EXIT
END DO
THETAG=DASIN(DBLE(1.D0/VMAX))		!THEORETICAL CRITICAL ANGLE 

!PRINT *, 'THETAG,theta ',  THETAG*180./PI,  theta*180./pi, ENEPROTON
  
    IF(THETA.LT.THETAG.OR.ENEPROTON.LT.0.1) THEN
	DV=0. ;	DM=0.
	INDICATOR=-1		!THERE IS NO TRACK FORMATION 
	RETURN
	END IF				    
			  


I=1
DO			!LINEAR INTERPOLATION FOR RANGE CALCULATIONS
IF(ENEPROTON>ENES(I))THEN
I=I+1
CYCLE
ELSE
RANGESRIM=RAN(I-1)+(ENEPROTON-ENES(I-1))*(RAN(I)-RAN(I-1))/(ENES(I)-ENES(I-1))
EXIT
END IF
END DO

RANGE=RANGESRIM	!RANGE CALCULATED BY SRIM2000 PROGRAM WITH LINEAR INTERPOLATION 

WRITE(*,505) RANGE 
505 FORMAT(' ',' PROTON RANGE IN DETECTOR IN MICROMETERS',F10.4)

PRINT *, ' PLEASE WAIT'

PRINT *,  '   ' 
PRINT *,  '   ' 

CALL DINT3 (RANGE,0.D+0,RANGE,SKSL)  !NUMERICAL INTEGRATION

TIMEC=SKSL/VB	
!PRINT *,' TIMEC', TIMEC
!THE INTEGRAL CACLCULATES SKSL, THAT IS THE REMOVED LAYER NEEDED THAT SOLUTION ACHIEVES THE END POINT OF PARTICLE IN DETECTOR
!TIMEC IS THE TIME OF ETCHING NEEDED TO REACH THE ENDING POINT OF THE RANGE.
!DOES THE TRACK DEVELOPMENT START ON THE DETECTOR SURFACE ??
 						
VP=VT(RANGE)	!VP IS THE TRACK TO BULK ETCH RATIO ON THE DETECTOR SURFACE

  IF(VP*DSIN(THETA)<1.) THEN
  PRINT *,'TRACK FORMATION DOES NOT START ON THE ORIGINAL DETECTOR SURFACE'
  !DETERMINATION OF THE DEPTH HC WHERE THE TRACK DEVELOPMENT START	 
	Xc=0.D+0		!X IS DISTANCE ALONG THE TRACK
		
		DO
		
			IF(VT(RANGE-Xc)*DSIN(THETA).GE.1.)EXIT
		
			Xc=Xc+0.01
			IF(Xc.GE.RANGE) THEN
			INDICATOR=-1	  !TRACK IS NOT FORMED AT ALL
			RETURN	
			END IF
		END DO
									 
!HC IS THICKNES REMOVED WHEN THE TRACK START TO DEVELOP


	  HC=Xc*DSIN(THETA)
      IF(HC.GE.REMOVED)  THEN
	  INDICATOR=-1		!THE TRACK HAS NOT BEEN DEVELOPED, INDICATOR=-1
	  
      PAUSE 'THERE IS NOT TRACK DEVELOPMENT - PRESS ENTER' 

	  RETURN
	  END IF
	  RANGE=RANGE-Xc					!LOWERING THE RANGES
 	  REMOVED=REMOVED-HC				!LOWERING THE REMOVED THICKNESS FOR HC
	  TIME_ETCHING=TIME_ETCHING-HC/VB	!LOWERING THE ETCHING TIME 

	  CALL DINT3(RANGE,0.D+0,RANGE,SKSL)  	   
	  TIMEC=SKSL/VB	!THE TIME OF ETCHING NEEDED TO REACH THE ENDING POINT OF THE RANGE.
END IF   !END THE BLOCK WHERE THE TRACK DEVELOPMENT DID NOT START AT THE SURFACE
	
 					   
	 
			RASTD=0.0d0
			IFLAG=0	    


	DO		!THIS LOOP CALCULATES THE DISTANCE THAT ETCHANT PASS INTO THE DETECTOR.
		IF(RASTD>=RANGE)THEN
		IFLAG=1
		EXIT
		END IF

		CALL DINT3(RANGE,0.D+0,RASTD,DB)
	
 		TEKVR=DB/VB
		IF(TEKVR.GE.TIME_ETCHING)EXIT
		RASTD=RASTD+0.001d0 
	END DO			    
	
IF(IFLAG==0)RASTD=RASTD-0.001D0
IF(IFLAG==1)RASTD=RANGE
  
!DISTANCE RASTD IS SPLITED IN TWO PARTS. FIRST PART IS DIVIDED IN "NSTEP" 

!SECOND PART IS DIVIDE IN NSTEP1, THE SIZE OF THE STEP IS DIFFERENT IN FIRST AND SECOND PART 
!PRINT *, ' FOR VERY FINE GRAPH TYPE   1'
!PRINT *, ' FOR MEDIUM FINE GRAPH TYPE 2'
!PRINT *, ' FOR COARSE GRAPH TYPE      3'
!READ *,  FINE
 FINE=1
IF(FINE.EQ.1.)THEN
AINTERVAL=0.01d0
IF(THETA*180./PI>88.)AINTERVAL=0.005d0
ELSE IF (FINE.EQ.2.) THEN
AINTERVAL=0.05d0
ELSE IF(FINE.EQ.3.)	 THEN
AINTERVAL=0.1d0
ELSE
AINTERVAL=0.01d0
PRINT *, 'PLOT THE FINEST GRAPH'
END IF


IF(THETA>85.D0*PI/180.D0)AINTERVAL=AINTERVAL/5.d0

IF(RASTD<RANGE-0.5D0*XMAX) THEN
MARK=1		
NSTEP=INT(RASTD/AINTERVAL)		!NUMBER OF STEPS
STEP=RASTD/NSTEP
NSTEPT=NSTEP+1
NDODATAK=0
ELSE

MARK=2

NSTEP=INT((RASTD-0.5D0*XMAX)/AINTERVAL)			!NUMBER OF STEPS IN THE FIRST PART

STEP=(RASTD-0.5D0*XMAX)/NSTEP					!STEP SIZE IN THE FIRST PART OF THE TRACK

NSTEP1=INT(0.5D0*XMAX/(AINTERVAL/100.D0))		!NUMBER OF STEPS IN THE SECOND PART   

STEP1=0.5D0*XMAX/NSTEP1						!STEP IN THE SECOND PART OF THE TRACK 

NDODATAK=10							!ten additional points if the track is overetched
NSTEPT=NSTEP+NSTEP1+1				!TOTAL NUMBER OF POINTS
									!THE RASTD IS DIVIDED IN NSTEPT INTERVALS
END IF



NUK=NSTEPT+NDODATAK		

PRINT * ,  ' PROGRAM CALCULATES ' , NUK , ' POINTS COORDINATES ON THE TRACK WALL'
										  
ALLOCATE (TRAGX(NUK),TRAGY1(NUK),TRAGY2(NUK),PRAVA(NUK),PRAVAN(1:KRUGA,NUK))
ALLOCATE (X1(NUK),Y1(NUK),DELTA(NUK),VT_OVER_VB(NUK) )

X1(1)=0.
Y1(1)=RANGE

IF(MARK==1)THEN
DO I=2,NSTEPT
X1(I)=STEP*DBLE(I-1)
Y1(I)=RANGE-X1(I)					
END DO
END IF
 
IF(MARK==2)THEN
DO I=2, NSTEP+1
X1(I)=STEP*DBLE(I-1)
Y1(I)=RANGE-X1(I)
END DO

DO I=NSTEP+2,NSTEPT
X1(I)=X1(NSTEP+1)+STEP1*DBLE(I-NSTEP-1)
Y1(I)=RANGE-X1(I)				
END DO
END IF
 	  DO I=1,NSTEPT
	  VT_OVER_VB(I)=VT(Y1(I))
  	  IF(VT_OVER_VB(I)<1.)VT_OVER_VB(I)=1.
	  DELTA(I)=DASIN(1./VT_OVER_VB(I))	 !LOCAL DEVELOPING ANGLE DELTA ALONG THE TRAJECTORY
      END DO


	   DO I=1,NSTEPT
	   CALL DINT3(RANGE,0.D+0,X1(I),TIME) 
	   TIME=TIME/VB											! TIME WHEN SOME POINT X IS REACH
	   OVERETCHED_THICKNESS=(TIME_ETCHING-TIME)*VB		 	   
	   TRAGX(I)=X1(I)+OVERETCHED_THICKNESS*DSIN(DELTA(I))	! X COORDINATE OF THE TRACK
	   TRAGY1(I)=OVERETCHED_THICKNESS*DCOS(DELTA(I))		! Y COORDINATE OF THE TRACK	 -UPPER BRANCH	
       TRAGY2(I)=-TRAGY1(I)									! LOWER BRANCH OF THE TRACK	  
	   PRAVA(I)=-DTAN(THETA)*TRAGX(I)+REMOVED/DCOS(THETA)	! PRAVA REPRESENTS THE POSTETCHING SURFACE
	  	   END DO
   250 FORMAT(' ' ,4(E18.10,2X))
 
IF(NDODATAK.NE.0)THEN
ORAKUGAO=(DELTA(NSTEPT)-DELTA(NSTEPT-1))/11.D0
tragx(nuk) = tragx(nstept)
tragy1(nuk)= tragy1(nstept)
tragy2(nuk)=-tragy1(nuk)
prava(nuk) = prava(nstept)
 
K=1
DO I=NSTEPT,NUK-1		!CALCULATES ROUNDED PART OF THE TRACK BETWEEN NSTEPT-1 AND LAST POINT

TRAGX(I)=RASTD+OVERETCHED_THICKNESS*DSIN(DELTA(NSTEPT-1)+K*ORAKUGAO)

TRAGY1(I)= OVERETCHED_THICKNESS*DCOS(DELTA(NSTEPT-1)+K*ORAKUGAO)

TRAGY2(I)=-TRAGY1(I)									
IF(THETA<PI/2.)PRAVA(I)=-DTAN(THETA)*TRAGX(I)+REMOVED/DCOS(THETA)		
K=K+1
END DO
END IF

  
IF(THETA<PI/2.) THEN	 !BLOCK RELATED FOR INCIDENT ANGLE <90 
 
	J=1
	 DO	!CALCULATES THE CROSS SECTION WITH THE UPPER BRANCH OF THE TRACK
     IF(PRAVA(J).LT.TRAGY1(J))EXIT
	 J=J+1
	 END DO
      	 
	 IGORNJI=J-1    
	  
CALL LINEAR_INTERPOLATION(REMOVED,THETA,TRAGX(J-1),TRAGY1(J-1),TRAGX(J),TRAGY1(J),XPRES1,YPRES1)


TRAGX(J-1)=XPRES1		 
TRAGY1(J-1)=YPRES1
TRAGY2(J-1)=-TRAGY1(J-1)
PRAVA(J-1)=YPRES1
 
IGRANA=1

 DO	!CALCULATES THE CROSS SECTION WITH THE LOWER PART OF THE TRACK
 IF(PRAVA(J).LT.TRAGY2(J))EXIT
 J=J+1
 IF(J>NUK)THEN
 IGRANA=-1
 EXIT
 END IF
 END DO

 IF(IGRANA==1)THEN
 CALL LINEAR_INTERPOLATION(REMOVED,THETA,TRAGX(J-1),TRAGY2(J-1),TRAGX(J),TRAGY2(J),XPRES2,YPRES2)

IDONJI=J 
 
TRAGX(J)=XPRES2
TRAGY1(J)=-YPRES2
TRAGY2(J)=YPRES2
PRAVA(J)=YPRES2

NGORNJI=NUK-IGORNJI +1		!NUMBER OF POINTS IN THE UPPER PART OF THE TRACK  
NDONJI =NUK-IDONJI  +1		!NUMBER OF POINTS IN THE LOWER PART OF THE TRACK 
NTOTAL=NGORNJI+NDONJI		!TOTAL NUMBER OF POINTS IN THE TRACK
END IF   
 
ALLOCATE (RTRAGX(NTOTAL),RTRAGY(NTOTAL))

RTRAGY(1:NGORNJI)=TRAGY1(IGORNJI:NUK)
RTRAGX(1:NGORNJI)=TRAGX(IGORNJI:NUK)
 K=1
 DO I=NGORNJI+1, NTOTAL
 RTRAGY(I)=TRAGY2(NUK+1-K)		!ARRAYS TRAGX AND RTRAGY ARE WHOLLE TRACK COORDINATES IN ONE ARRAY
 RTRAGX(I)=TRAGX (NUK+1-K)		
 K=K+1
 END DO
 
 END IF


 IF(THETA==PI/2.)THEN !NORMAL INCIDENT ANGLE 
 XPRES1 = REMOVED
 XPRES2 = REMOVED
     J=1
	 
	 DO	  
     IF(XPRES1.LT.TRAGX(J))EXIT
	 J=J+1
	 END DO
      	 				   
	 IGORNJI=J-1
	 IDONJI=IGORNJI
YPRES1=TRAGY1(J)
YPRES2=-YPRES1
NTOTAL = 2*(NUK-IGORNJI)
NGORNJI=NUK-IGORNJI +1 


 
 ALLOCATE (RTRAGX(NTOTAL),RTRAGY(NTOTAL))

RTRAGY(1:NGORNJI)=TRAGY1(IGORNJI:NUK)
RTRAGX(1:NGORNJI)=TRAGX(IGORNJI:NUK)


 K=1
 DO I=NGORNJI+1, NTOTAL
 RTRAGY(I)=TRAGY2(NUK+1-K)		!ARRAYS TRAGX AND RTRAGY ARE WHOLLE TRACK COORDINATES IN ONE ARRAY
 RTRAGX(I)=TRAGX (NUK+1-K)		
 K=K+1
 END DO
END IF  !END OF THE BLOCK FOR NORMAL INCIDENT ANGLE  


IF(THETA<PI/2)THEN  !OBLIQUE INCIDENT ANGLE 
 	IF(IGRANA==-1)THEN  !THERE IS NO CROSS WITH THE LOWER PART OF THE TRACK. 
						!CALCULATION OF THE SECOND CROSS WITH THE UPPER PART. TIPICAL FOR SMALL INCIDENT ANGLES 
	J=NUK									

	DO
    IDONJI=J	
	IF(PRAVA(J).LT.TRAGY1(J))EXIT
	J=J-1
	END DO

CALL LINEAR_INTERPOLATION(REMOVED,THETA,TRAGX(J),TRAGY1(J),TRAGX(J+1),TRAGY1(J+1),XPRES2,YPRES2)

DEALLOCATE (RTRAGX ,RTRAGY ) 
IDONJI=IDONJI+1

TRAGX(J+1)=XPRES2		
TRAGY1(J+1)=YPRES2
TRAGY2(J+1)=-TRAGY1(J+1)
PRAVA(J+1)=YPRES2


NTOTAL=IDONJI-IGORNJI + 1


 
ALLOCATE (RTRAGX(NTOTAL),RTRAGY(NTOTAL))

  
 do i=1,ntotal
 rtragx(i)=tragx (igornji+i-1)
 rtragy(i)=tragy1(igornji+i-1)
 end do
END IF
END IF  !END OF BLOCK FOR OBLIQUE INCIDENT ANGLE  

		 
DV=SQRT((XPRES1-XPRES2)**2+(YPRES1-YPRES2)**2)			 
DMAJOR=DV				!MAJOR AXIS OF THE TRACK 


AX=MAXVAL(RTRAGX)


Z0=REMOVED/DSIN(THETA)		!z0 is a point where post etched surface cut the trajectory of particles
							!ROTATE TRACK FROM HORIZONTAL TO VERTICAL POSITION
UGAOROTACIJE=PI-THETA		!THE ANGLE OF ROTATION

 
ALLOCATE (RX(NTOTAL),RY(NTOTAL))      

 
DO I=1, NTOTAL		!ROTATION
RX(I)= RTRAGX(I)*COS(UGAOROTACIJE)+RTRAGY(I)*SIN(UGAOROTACIJE)
RY(I)=-RTRAGX(I)*SIN(UGAOROTACIJE)+RTRAGY(I)*COS(UGAOROTACIJE)
END DO

TRAGCENTAR=(MINVAL(RX)+MAXVAL(RX))/2.

RY=RY-RY(1)			!SHIFTING THE TRACK IN THE CENTER OF THE SCREEN
RX=RX-TRAGCENTAR
 Dubina=DABS(MINVAL(RY))
 DEPTH=DUBINA
 PRINT *, 'TRACK DEPTH (um) ', DEPTH   !TRACK DEPTH


 
    DO I=2,NTOTAL                !WRITE TRACK PROFILE 
	WRITE(765,*)RX(I),RY(I)
    END DO

 

!THE FOLLOWING PART CALCULATES MINOR AXIS. NEED 3-D CONSIDERATION
!ALSO PLOT OPENING CONTOUR

IF(THETA<PI/2) THEN !BLOCK TO PLOT TRACK CONTOUR FOR OBLIQUE INCIDENT ANGLE 
M=NUK

NKONTURA=IDONJI-IGORNJI+1 	!TOTAL NUMBER OF THE POINTS ON CONTOUR

ALLOCATE (XOTVOR(NKONTURA),YOTVOR(NKONTURA))  !COORDINATES OF THE POINTS OF TRACK OPENING

YMAX=0.

K=1
DO I=IGORNJI, IDONJI
XOTVOR(K)=(Z0-TRAGX(I))/DCOS(THETA)
YOTVOR(K)=SQRT(TRAGY2(I)**2-PRAVA(I)**2)
IF(YOTVOR(K)>YMAX) YMAX=YOTVOR(K)
K=K+1
END DO										  


XCENTAR= (MINVAL(XOTVOR) + MAXVAL(XOTVOR))/2.

XOTVOR=XOTVOR-XCENTAR	!SHIFTING THE CONTOURE IN THE CENTER OF THE SCREEN

END IF  !END OF BLOCK FOR PLOTTING OF CONTOUR FOR OBLIQUE INCIDENT ANGLE 

  
!***************************************************************************
!FOLLOWING PART IS RELATED TO OPTICS  AND 3-D TRACK PRESENTATION
IF(THETA<PI/2.) THEN !OBLIQUE INCIDENT ANGLE 
  
IF(IGRANA==1)THEKRAJ=MAXVAL(RTRAGX) 

AKO=-DTAN(THETA)
	
ANO=REMOVED/DCOS(THETA)    	 

 STEPANO=0.001		    
   
 DINTERVAL1=THEKRAJ-Z0

!IF(THEKRAJ>Z0) THEN
INDIKATORGRANA=1
Z00=THEKRAJ	
!ELSE		 
RASTOMAX=-1.0E5
RASTOMAX1=0.
STEPANO=0.001   
NAZNAKA=0
DO
I=1
DO				
YN=AKO*TRAGX(I)+ANO		 
IF(YN<TRAGY1(I)) EXIT
I=I+1
IF(I>NUK)THEN
NAZNAKA=1
EXIT
END IF
END DO
 	 
IF(NAZNAKA==1)EXIT
ANO=ANO + STEPANO
END DO
ANO=ANO	- STEPANO   

RASTOMAX1=ANO*Dcos(THETA)-REMOVED 
Z00= (REMOVED+rastomax1)/DSIN(THETA)  
DINTERVAL1=Z00-Z0    
!END IF   
   
DELTAZ=DINTERVAL1/DBLE(FLOAT(KRUGA)-1.)	 
!FORMATION THE LOOPS IN 3-D				 
!ALL LOOPS HAVE THE SAME NUMBER OF POINTS

DO K=1,KRUGA			    
	DO I=1,NUK								   
	PRAVAN(K,I)=-DTAN(THETA)*TRAGX(I)+(REMOVED+DELTAZ*(K-1)*DSIN(THETA) )/DCOS(THETA)
 	END DO								 
END DO
 
DISTANCE=0.
INDEX=0

DO K=1,KRUGA  

	 INDIKATOR=1
	 J=1
	 DO	!CALCULATES THE CROSS SECTION WITH THE UPPER BRANCH OF THE TRACK
     IF(PRAVAN(K,J).LT.TRAGY1(J))EXIT
	 J=J+1
	 IF(J>NUK) THEN
	 INDIKATOR=-1		
	 EXIT
	 END IF
	 END DO
 CALL LINEAR_INTERPOLATION(REMOVED+DELTAZ*(K-1)*dsin(theta),THETA,TRAGX(J-1),TRAGY1(J-1),TRAGX(J),TRAGY1(J),PRESNGX(K),PRESNGY(K))
 
INDIKATOR=1

 DO	!CALCULATES THE CROSS SECTION WITH THE LOWER PART OF THE TRACK
  IF(PRAVAN(K,J).LT.TRAGY2(J))EXIT
   J=J+1
      IF(J>=NUK)THEN
      INDIKATOR=-1
      EXIT
      END IF
 END DO


IF(INDIKATOR==1)THEN
CALL LINEAR_INTERPOLATION(REMOVED+DELTAZ*(K-1)*dsin(theta),THETA,TRAGX(J-1),TRAGY2(J-1),TRAGX(J),TRAGY2(J),PRESNDX(K),PRESNDY(K))
END IF


IF(INDIKATOR==-1)THEN  !THERE IS NO CROSS WITH THE LOWER PART OF THE TRACK. 
						!CALCULATION OF THE SECOND CROSS WITH THE UPPER PART. TIPICAL FOR SMALL INCIDENT ANGLES 
	J=NUK									
					!UPER BRANCH IS CUT TWO TIMES- VERY SMALL INCIDENT ANGLE, PROBABLY TRACK IS NOT SEEN UNDER MICROSCOPE
	INDIKATOR=1
	DO
    IDONJI=J	
	IF(PRAVAN(K,J).LT.TRAGY1(J))EXIT
	J=J-1
	IF(J<=0)THEN
	INDIKATOR=-1		
	EXIT
	END IF
	END DO

 
IF(INDIKATOR==1)THEN
CALL LINEAR_INTERPOLATION(REMOVED+DELTAZ*(K-1)*dsin(theta),THETA,TRAGX(J),TRAGY1(J),TRAGX(J+1),TRAGY1(J+1),PRESNDX(K),PRESNDY(K))
END IF
END IF
 
DINTERVAL=-(PRESNGX(K)-PRESNDX(K))/DBLE(REAL(NPOINT-1))
 
 
DO  L=1,NPOINT		 
X= PRESNGX(K)+(L-1)*DINTERVAL
XP=X						 
YP=-DTAN(THETA)*X+(REMOVED+(K-1)*DELTAZ*DSIN(THETA))/DCOS(THETA)
 M=1
	DO
	IF(XP<TRAGX(M))EXIT
	M=M+1
	if(m>=nuk)exit
	END DO  

  	  		 			
YT= TRAGY1(M)+(TRAGX(M)-XP)*((TRAGY1(M-1)-TRAGY1(M))/(TRAGX(M)-TRAGX(M-1)))

  
XOT=((REMOVED+DELTAZ*(K-1)*DSIN(THETA))/DSIN(THETA)-XP)/DCOS(THETA)  
 
IF((YT**2-YP**2)<0)THEN
YOT=0.
ELSE
YOT=DSQRT(YT**2-YP**2)
END IF


INDEX=INDEX+1
YY(INDEX,1 )=XOT-DELTAZ*(K-1)*DSIN(THETA)/DTAN(THETA)
YY(INDEX,2 )=YOT
YY(INDEX,3)=-YOT
YY(INDEX,4)=-(K-1)*DELTAZ*DSIN(THETA)			   
END DO		 

END DO		 
  
ZKOORD=0.
DO I=1, NKONTURA
WRITE(766,1517)XOTVOR(I)+XCENTAR,YOTVOR(I)  !, ZKOORD
END DO

DO I=NKONTURA,1,-1
WRITE(766,1517)XOTVOR(I)+XCENTAR,-YOTVOR(I)	!, ZKOORD
END DO



DM=2.D+0*YMAX
DMINOR=DM		!MINOR AXIS OF THE TRACK


IAX=INT(AX)
IF(IAX==0)IAX=1

PX0=0.
PY0=0.

PX=RASTD
PY=0.

PRX= PX*COS(UGAOROTACIJE)
PRY=-PX*SIN(UGAOROTACIJE)

PRY=PRY-RY(1)+REMOVED			!SHIFTING THE TRACK IN THE CENTER OF THE SCREEN
PRX=PRX-TRAGCENTAR

PX0=PX0-TRAGCENTAR
PY0=PY0-RY(1)+REMOVED

 
DEALLOCATE (XOTVOR,YOTVOR)
DEALLOCATE (TRAGX,TRAGY1,TRAGY2,PRAVA )
DEALLOCATE (X1,Y1,DELTA,VT_OVER_VB)
DEALLOCATE (RTRAGX,RTRAGY, RX,RY)     

END IF  !END OF THE BLOCK FOR OLBIQUE INCIDENCE 

IF(THETA==PI/2.) THEN !BLOCK FOR NORMAL INCIDENCE 
ALLOCATE(PRXK(1:KRUGA),PRYK(1:KRUGA) )  
ALLOCATE (XOTVOR(NPOINT),YOTVOR(NPOINT))
 

THEKRAJ=MAXVAL(TRAGX)
 
DINTERVAL1=THEKRAJ-REMOVED
DELTAZ=DINTERVAL1/DBLE(FLOAT(KRUGA)-1.)	
 
DO I=1,KRUGA
PRXK(I)=REMOVED+(I-1)*DELTAZ    !THE FIRST PLANE IS ON THE TRACK CONTOUR 
 							 
								!THE LAST PLANE IS AT THE END OF THE TRACK 
DELTAFI=PI/DBLE(REAL((NPOINT-1)))
   J=1
   DO
    IF(PRXK(I)<TRAGX(J))EXIT
     J=J+1
      IF(J==NUK)EXIT
       END DO

  
PRYK(I)=TRAGY1(J-1)	-(TRAGY1(J-1)-TRAGY1(J) )/(TRAGX(J)-TRAGX(J-1))*(PRXK(I)-TRAGX(J-1))
  
 DO  L=1,NPOINT	
  XOT=PRYK(I)*COS(DELTAFI*(L-1))
   YOT=PRYK(I)*SIN(DELTAFI*(L-1))
     INDEX=INDEX+1
     YY(INDEX,1 )=XOT-DELTAZ*K*Dcos(theta) 
    YY(INDEX,2 )=YOT
   YY(INDEX,3)=-YOT
   YY(INDEX,4)=-(I-1)*DELTAZ*DSIN(THETA)			   
    IF(I==1) 	WRITE(766,*)XOT,YOT 	  
   END DO
	 
 DO  L=NPOINT,	1, -1			
  XOT=PRYK(I)*COS(DELTAFI*(L-1))
   YOT=PRYK(I)*SIN(DELTAFI*(L-1))
	
  	 IF(I==1) WRITE(766,*)XOT,-YOT    
      END DO

END DO	   

  
 

IAX=INT(AX)
IF(IAX==0)IAX=1
 
DM=DV
END IF	  !END OF BLOCK FOR NORMAL INCIDENCE 

!WRITE(*,81) IAX
!81 FORMAT(' ','THE VERTICAL BAR REPRESENTS  ',I3,' um')

 
 KORX=YY(1:KRUGA*NPOINT,1)
 KORY=YY(1:KRUGA*NPOINT,2)
 KOR_Y=YY(1:KRUGA*NPOINT,3)
 KORZ=YY(1:KRUGA*NPOINT,4)
 
 J=0
 DO K=1,KRUGA 

 DO I=1,NPOINT
  J=J+1
  KOORDINATE_3DX(J ) = KORX(I+NPOINT*(K-1))
   KOORDINATE_3DY(J ) = KORY(I+NPOINT*(K-1))
    KOORDINATE_3DZ(J ) = KORZ(I+NPOINT*(K-1))
 END DO

DO I=NPOINT -1,2,-1
 J=J+1
  KOORDINATE_3DX(J ) = KORX(I+NPOINT*(K-1))
   KOORDINATE_3DY(J ) = KOR_Y(I+NPOINT*(K-1))
    KOORDINATE_3DZ(J ) = KORZ(I+NPOINT*(K-1))
 END DO

END DO 	 	 

 
    
IF(THREEDIM=='Y')THEN   
 
DO I=1,N3D
WRITE(1519,1517)KOORDINATE_3DX(I),KOORDINATE_3DY(I),KOORDINATE_3DZ(I)
END DO  

  
1517 FORMAT(' ' ,4(F12.7,2X))
END IF 
 NPOINT2=2*NPOINT-2 
KRUGOVA=N3D/NPOINT2 
NC=(KRUGOVA-1)*(NPOINT2)  !NUMBER OF POLYGONS REPRESENTING THE TRACKS
 
ALLOCATE (FINRES(NC,9)) 
 	  
CALL Track_optics_P(N3D,NC,NPOINT,KOORDINATE_3DX,KOORDINATE_3DY,KOORDINATE_3DZ,FINRES, crnideo)
 
!PAUSE  'PRESS ENTER TO GET TRACK APPEARANCE'
 

 
END SUBROUTINE DETPROTON

				   







