SUBROUTINE LINEAR_INTERPOLATION(REM,THETA,X1,Y1,X2,Y2,XP,YP)
DOUBLE PRECISION REM,X1,Y1,X2,Y2,XP,YP,THETA
  BROJILAC=(X1*Y2-X2*Y1)/(X1-X2)- REM/COS(THETA)
 BIMANILAC=-TAN(THETA)-(Y1-Y2)/(X1-X2)
 XP=BROJILAC/BIMANILAC
 YP=-TAN(THETA)*XP+REM/COS(THETA)
END SUBROUTINE	LINEAR_INTERPOLATION
