SUBROUTINE PRELOMGR(PX,PY,PZ,ENX,ENY,ENZ,P1X,P1Y,P1Z)
! CALCULATE THE DIRECTION OF REFRACTED RAY FROM LESS DENSER TO   DENSER MEDIA
! PX,PY,PZ INCIDENT DIRECTION 
! INDEX,  INDEX OF REFRACTION 
! ENX,ENY,ENZ  NORMAL ON THE SURFACE AT THE POINT OF REFRRACTION 
! P1X,P1Y,P1Z  NEW DIRECTION AFTER REFRACTION 

IMPLICIT REAL (8) (A-H, O-Z)
REAL (8) INDEX
INDEX=1.5
 SKPROIZVOD=PX*ENX+PY*ENY+PZ*ENZ
 ALFA=DACOS(SKPROIZVOD)			!INCIDENT ANGLE
 BETA=DASIN(DSIN(ALFA)/INDEX)	!ANGLE OF REFRACTION
 DETA1=DETA3(ENX,ENY,ENZ,PX,PY,PZ,(PY*ENZ-PZ*ENY),(PZ*ENX-PX*ENZ),(PX*ENY-PY*ENX))
DETAX=DETA3(DCOS(BETA),ENY,ENZ,DCOS(BETA-ALFA),PY,PZ,0.D0,(PZ*ENX-PX*ENZ),(PX*ENY-PY*ENX))
DETAY=DETA3(ENX,DCOS(BETA),ENZ,PX,DCOS(BETA-ALFA),PZ,(PY*ENZ-PZ*ENY),0.D0,(PX*ENY-PY*ENX))
DETAZ=DETA3(ENX,ENY,DCOS(BETA),PX,PY,DCOS(BETA-ALFA),(PY*ENZ-PZ*ENY),(PZ*ENX-PX*ENZ),0.D0)
 IF(DETA1==0.)THEN
 P1X=0.
 P1Y=0.
 P1Z=1.
 ELSE
 P1X=DETAX/DETA1
P1Y=DETAY/DETA1
P1Z=DETAZ/DETA1
END IF
END SUBROUTINE PRELOMGR



 